name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build
        run: |
          npm install
          npm run build
      - name: 'Upload artifact for deployment job'
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
